CREATE DATABASE TicTacToeData;

CREATE USER tictactoeuser WITH PASSWORD 'tictactoepassword';

GRANT ALL PRIVILEGES ON TicTacToeData TO tictactoeuser;

CREATE TABLE TicTacToeGames
(
	InstanceId    bigint			PRIMARY KEY,
	Description   varchar(500)		NOT NULL,
	GridSize      integer			NOT NULL,
	Status        integer			NULL DEFAULT NULL,
    CreatedDate   timestamptz		NOT NULL DEFAULT (current_timestamp at time zone 'UTC'),
    CompletedDate timestamptz		NULL DEFAULT NULL
);

CREATE TABLE TicTacToeData
(
    Id          bigint			PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CreatedDate timestamptz		NOT NULL DEFAULT (current_timestamp at time zone 'UTC'),
    InstanceId  bigint			NOT NULL REFERENCES TicTacToeGames (InstanceId)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    MoveNumber  integer			NOT NULL,
    CellIndex   integer			NOT NULL,
    CellContent integer			NOT NULL	
);

\quit