CREATE DATABASE "TicTacToeDb";

\c "TicTacToeDb"

CREATE TABLE "TicTacToeGames"
(
    "InstanceId"    bigint          PRIMARY KEY,
    "Description"   varchar(500)    NOT NULL,
    "GridSize"      integer         NOT NULL,
    "Status"        integer         NULL DEFAULT NULL,
    "CreatedDate"   timestamptz     NOT NULL DEFAULT (current_timestamp at time zone 'UTC'),
    "CompletedDate" timestamptz     NULL DEFAULT NULL
);

CREATE TABLE "TicTacToeData"
(
    "Id"            bigint          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "CreatedDate"   timestamptz     NOT NULL DEFAULT (current_timestamp at time zone 'UTC'),
    "InstanceId"    bigint          NOT NULL,
    "MoveNumber"    integer         NOT NULL,
    "CellIndex"     integer         NOT NULL,
    "CellContent"   integer         NOT NULL,
    CONSTRAINT "FK_TicTacToeGames_InstanceId"
    FOREIGN KEY ("InstanceId")
    REFERENCES "TicTacToeGames"("InstanceId")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

\quit