version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build: ./WebAPI
    #build:
    #  context: .
    #  dockerfile: WebAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8443:8443"

  blazorserverapp:
    image: ${DOCKER_REGISTRY-}blazorserverapp
    build: ./BlazorServerApp
    #build:
    #  context: .
    #  dockerfile: BlazorServerApp/Dockerfile
    ports:
      - "8090:8080"
      - "8453:8443"
    depends_on:
      webapi:
        condition: service_started