version: '3.4'

services:
  webapi:
    environment:
      - BUILD_CONFIGURATION=Debug
      - ASPNETCORE_ENVIRONMENT=Development-Docker
      - ASPNETCORE_URLS=http://+:80"
      - TicTacToeDataConnString=${TicTacToeDataConnString}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  blazorserverapp:
    environment:
      - BUILD_CONFIGURATION=Debug
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80"
      - TicTacToeWebApiEndPoint=${TicTacToeWebApiEndPoint}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
