# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    # Service containers to run with `runner-job`
    # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 43594 on service container to the host
          - 43594:43594
          
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Login to Postgres
      run: |
        sudo /etc/init.d/postgresql restart
        export PGHOSTADDR=127.0.0.1
        echo $PGHOSTADDR
        export PGPORT=43594
        echo $PGPORT
        export PGHOST=43594
        echo $PGHOST
        export PGUSER=postgres
        echo $PGUSER
        export PGPASSWORD=postgres
        echo $PGPASSWORD
        psql -l
        /c testdb
        /dt
        /quit
    - name: Test
      run: dotnet test --no-build --verbosity normal
