# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mlnetJob:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Check for Unprocessed Training Data
      run: |
        if [ -d "./TicTacToeML" ]; then
            if [ -d "./TicTacToeML/TrainingData" ]; then
                if [ -d "./TicTacToeML/TrainingData/Queue" ]; then
                    if [ "$(ls ./TicTacToeML/TrainingData/Queue/*.csv)" ]; then
                        echo "There is new Training Data"
                    else
                        echo "There is NO new Training Data"
                        echo "::exit 1"
                    fi
                fi
            fi
        fi

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
        
    - name: Run ML Pipeline
      run: dotnet test ./MLPipelines/MLPipelines.csproj --no-build --verbosity normal --settings /home/runner/work/Tic-Tac-Toe/Tic-Tac-Toe/MLPipelines/MLPipeline.runsettings

    - name: Test Git Commit
      run: |
          git status
          git add TicTacToeML/MLModels
          git add TicTacToeML/TrainingData
          git status
          git config --global user.name 'JosephWee'
          git config --global user.email 'JosephWee@users.noreply.github.com'
          git commit -m "$env:GITHUB_WORKFLOW \#$env:GITHUB_RUN_NUMBER - Commit $env:GITHUB_SHA pushed by $env:GITHUB_ACTOR"
          git push origin
