# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mlnetJob:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run ML Pipeline
      run: dotnet test ./MLPipelines/MLPipelines.csproj --no-build --verbosity normal --settings /home/runner/work/Tic-Tac-Toe/Tic-Tac-Toe/MLPipelines/MLPipeline.runsettings

    - name: Commit and Push File Changes
      run: |
          DoCommit=0
          gitstatus=$(git status)
          
          if [[ "$gitstatus" == *"nothing to commit, working tree clean"* ]]
          then
            echo "Block 1"
            DoCommit=0
          else
            echo "Block 2"
            if [[ "$gitstatus" == *"TicTacToeML/MLModels/"*".zip"* ]]
            then
                echo "Block 3"
            fi

            if [[ "$gitstatus" == *"TicTacToeML/TrainingData/Processed/"*".csv"* ]]
            then
                echo "Block 4"
            fi

            if [[ "$gitstatus" == *"TicTacToeML/TrainingData/Rejected/"*".csv"* ]]
            then
                echo "Block 5"
            fi
          fi
          
