# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mlnetJob:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run ML Pipeline
      run: dotnet test ./MLPipelines/MLPipelines.csproj --no-build --verbosity normal --settings /home/runner/work/Tic-Tac-Toe/Tic-Tac-Toe/MLPipelines/MLPipeline.runsettings

    - name: Commit and Push File Changes
      run: |
          DoCommit=0
          gitstatus=$(git status)
          
          echo $gitstatus

          if [[ "$gitstatus" == *"Changes not staged for commit"* ]]
          then
            echo "Block 1"
            
            if [[ "$gitstatus" == *"TicTacToeML/MLModels/"*".zip"* ]] || [[ "$gitstatus" == *"TicTacToeML/TrainingData/Processed/"*".csv"* ]] || [[ "$gitstatus" == *"TicTacToeML/TrainingData/Rejected/"*".csv"* ]]
            then
                echo "Block 2"
                
                git add TicTacToeML/MLModels
                git add TicTacToeML/TrainingData
                
                gitstatus=$(git status)

                if [[ $gitstatus == *"Changes to be committed"* ]]
                then
                    echo "Block 3"
                    DoCommit=1
                fi
            fi
          fi

          if [ $DoCommit -eq 1 ]
          then
                echo "Changes detected"
                git config --global user.name 'JosephWee'
                git config --global user.email 'JosephWee@users.noreply.github.com'
                git commit -m "WORKFLOW:$GITHUB_WORKFLOW JOB:$GITHUB_JOB RUN:$GITHUB_RUN_NUMBER triggered by Commit $GITHUB_SHA pushed by $GITHUB_ACTOR"
                git push origin
          else
                echo "No Changes detected"
          fi
